### ISSUE TITLE
Consider using Cache to speed up CI builds

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#382]
### Environment

-   Pythonnet version: All
-   Python version: All
-   Operating System: CI

### Details

Keep Cache of `pip` and `packages` to avoid downloading again.

travis:
```yaml
before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
    - packages
```

AppVeyor:
```yaml
cache:
  # Preserve `packages` directory; will reset if `packages.config` is modified
  - packages -> **\packages.config
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'
```
